### ISSUE TITLE
Forecast ETL Performance

### ISSUE THREAD

**Issue by amehta-scottlogic** [ECMWFCode4Earth/vAirify#10]
- Update how measurement time is calculated in forecast data (can just use valid time)
- Rename measurement time?
- Look at if doing less interpolation calls improves performance
- Look into threading

Test Checklist:
- [x] Test Analysis & discussion with developer
- [x] Write Test Cases / Charters
- [x] Test Cases & Charters Reviewed
- [x] Test Cases / Charters Executed
- [x] Regression tests executed
- [ ] Write Automation tests for regression

**Comment by mwalker-scottlogic** [comment]
### Test Analysis

- Run regression tests to ensure that nothing has functionally changed as a result of this work
- No test case required, but exploratory testing to verify it is anecdotally faster

Test Charter:

-[Explore backend performance to discover surprises](https://github.com/ECMWFCode4Earth/vAirify/wiki/Explore-backend-performance-to-discover-surprises)

**Comment by mwalker-scottlogic** [comment]
Only regression tested forecast db as in_situ is too unstable
