### ISSUE TITLE
As a system user the latest version of the vAirify API is deployable to the linux machine so it can be used

### ISSUE THREAD

**Issue by lincent** [ECMWFCode4Earth/vAirify#100]
Requires the output of this story : #22 

Containerise the API

Acceptance Criteria:

- Dockerfile made for the API
- Github action to build new image
- Update compose files (local and deployment version)
- Update all docs as necessary
- Investigate hot reloading for local dev using the docker image
- Whenever a change is made to the API and checked into main the CI pipeline we can deploy this latest version into the linux machine.
- Testing we can hit the API and get data back
- This does not include reworking the existing automated API tests to hit this deployed version, just checking it's deployed and works

**Comment by mwalker-scottlogic** [comment]
### Test Analysis

Test Cases required:

- check the GET to `http://127.0.0.1:8000/air-pollutant/forecast` is successful
  - 200 & returns data
  - compare to deployed database data
- check the GET to `http://127.0.0.1:8000/air-pollutant/measurements` is successful
  - 200 & returns data
  - compare to deployed database data
- check the GET to `http://127.0.0.1:8000/air-pollutant/measurements/summary` is successful
  - 200 & returns data
  - compare to deployed database data

**Comment by mwalker-scottlogic** [comment]
**GET to http://64.225.143.231/api/air-pollutant/forecast**
200 response with data

- Postman request: 
http://64.225.143.231/api/air-pollutant/forecast?location_type=city&valid_time_from=2024-06-25T12%3A00%3A00%2B00%3A00&valid_time_to=2024-06-30T12%3A00%3A00%2B00%3A00&base_time=2024-06-25T12%3A00%3A00%2B00%3A00&location_name=London


![Image](https://github.com/ECMWFCode4Earth/vAirify/assets/110834691/601dd6ed-d56f-47a1-896a-b247d07e22a3)


- MongoDB Query: 
```
{$and: 
	[ 
		{forecast_base_time: new ISODate("2024-06-25T12:00:00.000+00:00")},
    {forecast_valid_time: 
			{
				$gte: new ISODate('2024-06-25T12:00:00.000+00:00'),
      	$lte: new ISODate('2024-06-30T12:00:00.000+00:00')
			}
		},
		{name: "London"}
	]
}
```

![Image](https://github.com/ECMWFCode4Earth/vAirify/assets/110834691/1b601ad1-9a4e-4923-b87f-f6c66a3fd664)

**GET to http://64.225.143.231/api/air-pollutant/measurements**
200 response with data

- Postman request:
- http://64.225.143.231/api/air-pollutant/measurements?location_type=city&api_source=OpenAQ&date_from=2024-06-25T13%3A00%3A00%2B00%3A00&date_to=2024-06-25T14%3A00%3A00%2B00%3A00&location_name=London

![Image](https://github.com/ECMWFCode4Earth/vAirify/assets/110834691/0a42eadc-3d0c-4195-81cf-614026a162db)
![Image](https://github.com/ECMWFCode4Earth/vAirify/assets/110834691/9539756d-e032-4950-bea5-41454547189f)

- MongoDB Query: 
```
{
  $and: [
    {location_type: "city"},
    {api_source: "OpenAQ"},
    {measurement_date: {
        $gte: ISODate("2024-06-25T13:00:00.000Z"),
        $lte: ISODate("2024-06-25T14:00:00.000Z")
      }
    },
    {location_name: "Ealing Horn Lane"}
  ]
}
```

![Image](https://github.com/ECMWFCode4Earth/vAirify/assets/110834691/d7be1bc2-4964-4522-9602-dadea6ecec47)

**GET to http://64.225.143.231/api/air-pollutant/measurements/summary**

- can't test this in the same way as the response does calculation on the database data, however it was a 200 response with data
