### ISSUE TITLE
[Demo Feedback] - Clearer indications of when forecast is different from real

### ISSUE THREAD

**Issue by amehta-scottlogic** [ECMWFCode4Earth/vAirify#107]
## Acceptance Criteria

- Include a toggle that flicks between:
  - Colour the pollutants that correspond to the maximum difference between forecast and measured overall AQI. I.e. if Overall AQI diff is 3 and pollutant1 has a AQI diff of 3, pollutant2 has a diff of 1, and pollutant3 has a diff of 3, pollutants 1 and 3 are coloured with their corresponding AQI level. AQI values are always highlighted.
  - All pollutant value grid cells coloured and AQI values
- Make it clear in diff column whether forecast is under/overperforming 
  - +/- sign should do it
  - forecast < measured (-)
  - forecast > measured (+)

  - Update the wiki page (and ensure added to the main sidebar)
  - When colouring the AQI values where there is a draw between different pollutants the AQI values displayed will be the ones with highest overall AQI value.
  - When there is still a draw (i.e. a 4 and a 6, and a 6 and a 4), the AQI values with a positive difference will be preferred

- Hue for the AQI levels match those at https://www.eea.europa.eu/themes/air/air-quality-index/index
- Re-decide if we should bold the text with lowered hues
- Add the colour hexes onto this ticket - check the contrast ratio is acceptable from an accessibility standpoint using https://webaim.org/resources/contrastchecker/?fcolor=E9EAE8&bcolor=2BB3BB

The hues used are:

cell-very-good = #50f0e5    ->    rgb(80, 240, 229)
cell-good = #50ccaa    ->    rgb(80, 204, 170)
cell-medium = #f0e641    ->    rgb(240, 230, 65
cell-poor = #ff505080    ->    rgba(255, 80, 80, 0.5)
cell-very-poor = #960032    ->    rgb(150, 0, 50)
cell-extremely-poor = #7d2181    ->    rgb(125, 33, 129)

Test Checklist:
- [x] Test Analysis & discussion with developer
- [x] Write Test Cases / Charters
- [x] Test Cases & Charters Reviewed
- [x] Test Cases Executed
- [x] Test Charters Executed
- [x] Regression tests executed
- [x] Automation Tests added to project

**Comment by mwalker-scottlogic** [comment]
### Test Analysis

- Verify pollutant values are assigned correct AQI colour band
  - check each band and pollutant corresponds to [chart](https://ecmwf-projects.github.io/copernicus-training-cams/proc-aq-index.html)
  - Automation test - create table with mocked data representing pollutant values from each band. Use either snapshot test or assert css to verify correct colours are used
- Verify toggle behaviour is correct
  - on toggle, 
    - 'Colour the pollutants that correspond to the maximum difference between forecast and measured overall AQI'
    - AQI values are always highlighted
  - when not toggled
    - All pollutant value grid cells coloured and AQI values
  - Automation test to use mocked data, and click the toggle and assert on the grid cells coloured
-  Verify diff column displays a +/- sign appropriately 
  - forecast < measured (-)
  - forecast > measured (+)
  - Automation to check this is displayed correctly with mocked data that represents the table

**Comment by mwalker-scottlogic** [comment]
### Finding - colour of overall AQI when multiple pollutants have the same diff

Steps to reproduce:
- Set up data where each pollutant has a diff between observed and measured of 1, e.g see below
```
 test('Test name TBC', async ({ summaryPage }) => {
        await summaryPage.setupPageWithMockData(
          [
            createForecastAPIResponseData({
              valid_time: '2024-07-08T03:00:00Z',
              no2: { aqi_level: CaseAQI1.aqiLevel, value: CaseAQI1.no2 },
              o3: { aqi_level: CaseAQI2.aqiLevel, value: CaseAQI2.o3 },
              pm2_5: { aqi_level: CaseAQI3.aqiLevel, value: CaseAQI3.pm2_5 },
              pm10: { aqi_level: CaseAQI4.aqiLevel, value: CaseAQI4.pm10 },
              so2: { aqi_level: CaseAQI5.aqiLevel, value: CaseAQI5.so2 },
            }),
          ],
          [
            createMeasurementSummaryAPIResponseData({
              measurement_base_time: '2024-07-08T03:00:00Z',
              no2: {
                mean: { aqi_level: CaseAQI2.aqiLevel, value: CaseAQI2.no2 },
              },
              o3: {
                mean: { aqi_level: CaseAQI3.aqiLevel, value: CaseAQI3.o3 },
              },
              pm2_5: {
                mean: { aqi_level: CaseAQI4.aqiLevel, value: CaseAQI4.pm2_5 },
              },
              pm10: {
                mean: { aqi_level: CaseAQI5.aqiLevel, value: CaseAQI5.pm10 },
              },
              so2: {
                mean: { aqi_level: CaseAQI6.aqiLevel, value: CaseAQI6.so2 },
              },
            }),
          ],
        )
        const expectedTableContents: string[][] = [
          [
            // AQI Level
            CaseAQI3.aqiLevel.toString(), // Forecast
            CaseAQI4.aqiLevel.toString(), // Measured
            '-1', // Diff
            // pm2.5
            CaseAQI3.pm2_5.toString(), // Forecast
            CaseAQI4.pm2_5.toString(), //Measured
            '08 Jul 03:00', //Time
            // pm10
            CaseAQI4.pm10.toString(), // Forecast
            CaseAQI5.pm10.toString(), // Measured
            '08 Jul 03:00', //Time
            // no2
            CaseAQI1.no2.toString(), // Forecast
            CaseAQI2.no2.toString(), // Measured
            '08 Jul 03:00', //Time
            // o3
            CaseAQI2.o3.toString(), // Forecast
            CaseAQI3.o3.toString(), // Measured
            '08 Jul 03:00', //Time
            // so2
            CaseAQI5.so2.toString(), // Forecast
            CaseAQI6.so2.toString(), // Measured
            '08 Jul 03:00', //Time
          ],
        ]

        await summaryPage.assertGridValues(expectedTableContents)
```

Expected:
- not defined
Actual:
- overall AQIhas taken the colours of specifically the pm2.5 values, in my test data this was not the largest discrep as pm2_5 was 22.5 & 26, whereas pm10 was 99 and 120

![Image](https://github.com/user-attachments/assets/256a9c46-56fb-4afb-88e7-36980c9b1604)

What is the expected behaviour in this scenario?

**Comment by mwalker-scottlogic** [comment]
### Test Analysis
Include a toggle that flicks between:
Colour the pollutants that correspond to the maximum difference between forecast and measured overall AQI. I.e. if Overall AQI diff is 3 and pollutant1 has a AQI diff of 3, pollutant2 has a diff of 1, and pollutant3 has a diff of 3, pollutants 1 and 3 are coloured with their corresponding AQI level. AQI values are always highlighted.
All pollutant value grid cells coloured and AQI values
The colours correspond to the chart : https://ecmwf-projects.github.io/copernicus-training-cams/proc-aq-index.html
Make it clear in diff column whether forecast is under/overperforming
+/- sign should do it
forecast < measured (-)
forecast > measured (+)
