### ISSUE TITLE
As a system user older versions of the cached grib files are removed

### ISSUE THREAD

**Issue by rstrange-scottlogic** [ECMWFCode4Earth/vAirify#137]
Currently we are storing GRIB files locally whenever we call the CAMs endpoint. 

Over time this will build up and we be storing a lot of historical files. Let's try and put a limit on the number of cached files, so that we manage this space usage.

Acceptance Criteria:
- There is a new environment variable STORE_GRIB_FILES which if set to False, or not set, will stop the caching of GRIB files after the forecast ETL run. 
- Files will still be cached if the variable is set to True
- This will not be set in the deployed environment

Integration test needed to check if file is deleted or not depending on variable setting

Test Checklist:
- [x] Test Analysis & discussion with developer
- [x] Write Test Cases / Charters
- [x] Test Cases & Charters Reviewed
- [x] Test Cases Executed
- [x] Test Charters Executed
- [x] Regression tests executed
- [x] Automation Tests added to project

**Comment by mwalker-scottlogic** [comment]
### Test Analysis

Picked up by a developer, automation created for:
- `file_not_stored_when_not_set_to_cache`
  - using flag set to false, check specific file doesn't exist after running main
  - check data is stored
- `test__grib_cache__file_not_stored_by_default`
  - not specifying flag,  check specific file doesn't exist after running main
  - check data is stored
- `test__grib_cache__file_stored_when_set_to_cache`
  - using flag set to true, check specific file does exist after running main
  -  check data is stored

**Comment by mwalker-scottlogic** [comment]
Manual test:

- `STORE_GRIB_FILES="True"`
-

**Comment by mwalker-scottlogic** [comment]
Set flag to false - run forecast etl with latest config

- expect no grib file to remain
- actual, 2 gribs during etl process
- PASS - both gribs removed
- 6273 documents in db modified within last 5 mins

No flag
- expect no grib file to remain
- actual, 2 gribs during etl process
- PASS - both gribs removed
- 6273 documents in db modified within last 5 mins

Set flag to true- run forecast etl with latest config

- expect grib files to remain
- actual, 2 gribs during etl process
- PASS both gribs remain
- 6273 documents in db modified within last 5 mins

**Comment by mnyamunda-scottlogic** [comment]
Looking good 💯
