### ISSUE TITLE
As a user I would like to see the pollution charts in a grid

### ISSUE THREAD

**Issue by tjohnson-scottlogic** [ECMWFCode4Earth/vAirify#145]
so that I can see more information at a time.

Acceptance Criteria

- On an HD desktop display (1920x1080) all possible charts can be displayed on a single page with no scrolling
- Show all pollutant graphs regardless of whether we have in-situ data
- Add AQI thresholds to the pollutant graphs

Test Checklist:
- [x] Test Analysis & discussion with developer
- [ ] Write Test Cases / Charters
- [ ] Test Cases & Charters Reviewed
- [ ] Test Cases Executed
- [ ] Test Charters Executed
- [x] Regression tests executed
- [ ] Automation Tests added to project

**Comment by mnyamunda-scottlogic** [comment]
Test analysis, 
- Verify a total of 6 charts are displayed without having to scroll. PW test runs at 1980x1080. Screenshot whole page?
- Verify that graphs still show on screen even with no in-situ data. 
  - PW test with just forecast data, snapshot will only contain black forecast line.
-  Verify that points on a chart are within the correct AQI colour band. Exploratory.

**Comment by mwalker-scottlogic** [comment]
Looks good to me Max

**Comment by mwalker-scottlogic** [comment]
Regression Tests Passed ✅ 

- Backend system tests

![Image](https://github.com/user-attachments/assets/3989ec5a-3dee-46cd-9c35-b5f5e2d8a842)

Frontend system tests

![Image](https://github.com/user-attachments/assets/2d2b3065-6430-4c8b-b495-3dd67166e5e2)

# #

[Playwright Regression 25.07.24.pdf](https://github.com/user-attachments/files/16379307/Playwright.Regression.25.07.24.pdf)
