### ISSUE TITLE
Prevent values of 9999 from entering the database

### ISSUE THREAD

**Issue by tjohnson-scottlogic** [ECMWFCode4Earth/vAirify#156]
Seb found in the OpenAQ code that if a station is not providing a value for a pollutant then a value of 9999 is assigned (code [here](https://github.com/openaq/openaq-fetch/blob/main/src/adapters/southkorea.js)).  These values should be filtered out of the ETL process such that we don't store them.

Acceptance Criteria
- There are no longer values of 9999 in the database, we filter out based on the original_value being 9999
- Delete all pollutant values from the deployed database where the original_value is 9999
- Ensure test are happy they have what they need before pulling the trigger on the delete

Test Checklist:
- [x] Test Analysis & discussion with developer
- [x] Write Test Cases / Charters
- [ ] Test Cases & Charters Reviewed
- [x] Test Cases Executed
- [ ] Test Charters Executed
- [x] Regression tests executed
- [x] Automation Tests added to project

**Comment by mwalker-scottlogic** [comment]
### Test Analysis

- Need to verify any existing `original_value` 9999s are removed from database
  - pre-deployment go and find existing examples of individual pollutants with values 9999 and verify the pollutant readings are removed post-deployment
  - pre-deployment go and find existing examples of documents where all pollutant values are 9999 and verify the documents are removed post-deployment
- Integration test required - mock openAQ response 
  - with pollutant value 9999, verify pollutant reading not added to the document with other valid pollutant readings
  - with all pollutant values for a site 9999, verify document not added to database

**Comment by mwalker-scottlogic** [comment]
{
  $and: [
    { "no2.original_value": 9999 },
    { "o3.original_value": 9999 },
    { "pm10.original_value": 9999 },
    { "pm2_5.original_value": 9999 },
    { "so2.original_value": 9999 }
  ]
}

{
  $or: [
    {
      "no2.original_value": {
        $gt: 500,
        $lt: 9999
      }
    },
    {
      "o3.original_value": { $gt: 500, $lt: 9999 }
    },
    {
      "pm10.original_value": {
        $gt: 500,
        $lt: 9999
      }
    },
    {
      "pm2_5.original_value": {
        $gt: 500,
        $lt: 9999
      }
    },
    {
      "so2.original_value": {
        $gt: 500,
        $lt: 9999
      }
    }
  ]
}

**Comment by mwalker-scottlogic** [comment]
- Before the change, there were 162 documents in the in_situ_data collection with all 5 pollutants registered as 9999
  - after, 0
![Image](https://github.com/ECMWFCode4Earth/vAirify/assets/110834691/97b86c81-0a97-41a8-af2e-718e6c2810d6)
both queries return no results in prod database now:
{
  $and: [
    { "no2.original_value": 9999 },
    { "o3.original_value": 9999 },
    { "pm10.original_value": 9999 },
    { "pm2_5.original_value": 9999 },
    { "so2.original_value": 9999 }
  ]
}

{
  $or: [
    { "no2.original_value": 9999 },
    { "o3.original_value": 9999 },
    { "pm10.original_value": 9999 },
    { "pm2_5.original_value": 9999 },
    { "so2.original_value": 9999 }
  ]
}

Before the deletion, I pulled every item in the database with pollutant values between 500 and 9998 to check they remain after the deletion of 9999 usign the below query:

{
  $or: [
    {
      "no2.original_value": {
        $gt: 500,
        $lt: 9999
      }
    },
    {
      "o3.original_value": { $gt: 500, $lt: 9999 }
    },
    {
      "pm10.original_value": {
        $gt: 500,
        $lt: 9999
      }
    },
    {
      "pm2_5.original_value": {
        $gt: 500,
        $lt: 9999
      }
    },
    {
      "so2.original_value": {
        $gt: 500,
        $lt: 9999
      }
    }
  ]
}

Running this query again after deletion, and comparing the spreadsheets (after sorting by name and measurement date), using a formula such as `=AND(C3:J3=L3:S3)` I was able to verify the data remained

![Image](https://github.com/ECMWFCode4Earth/vAirify/assets/110834691/a329ae45-8148-48ba-b4d7-4fa9bb6bbe2e)
