### ISSUE TITLE
As a user I want to be able to run the test suites easily

### ISSUE THREAD

**Issue by mwalker-scottlogic** [ECMWFCode4Earth/vAirify#178]
This ticket is to simplify the process for running the test files (currently, if you right click on system-tests in the backend it can't find the tests to run, so you need to run them individually) 

Test Checklist:
- [x] Test Analysis & discussion with developer
- [x] Write Test Cases / Charters
- [ ] Test Cases & Charters Reviewed
- [x] Test Cases Executed
- [ ] Test Charters Executed
- [ ] Regression tests executed
- [ ] Automation Tests added to project

**Comment by mwalker-scottlogic** [comment]
ran the backend system tests with one click:


![Image](https://github.com/user-attachments/assets/6352f6d3-09fc-4872-8181-d41f6391ec0f)

**Comment by mwalker-scottlogic** [comment]
### Test Analysis

- This can be tested by running the backend system-tests folder, if all the tests run and pass it is successful

**Comment by mnyamunda-scottlogic** [comment]
Looks good to me! 💯
