### ISSUE TITLE
Separate API from ETL

### ISSUE THREAD

**Issue by rstrange-scottlogic** [ECMWFCode4Earth/vAirify#180]
Currently the ETL depends on FastAPI and the API depends on GRIBs. This is because the code is too tightly coupled and will affect maintenance in the medium to long term.

We would to refactor the API and ETL codebases to split the folders up and separate the dependencies.

We could also look into removing conda from the API as the only reason we use this is due to GRIB file reads require it.

This just covers folder structure and dependency updates, no functionality should change.

Acceptance Criteria:
- All of the existing regression tests should continue to pass

Test Checklist:
- [x] Test Analysis & discussion with developer
- [ ] Write Test Cases / Charters
- [ ] Test Cases & Charters Reviewed
- [ ] Test Cases Executed
- [ ] Test Charters Executed
- [x] Regression tests executed
- [ ] Automation Tests added to project

**Comment by mwalker-scottlogic** [comment]
### Test Analysis

- Only automated and manual regression testing required
