### ISSUE TITLE
Make Logo

### ISSUE THREAD

**Issue by Ben-EJ** [ECMWFCode4Earth/vAirify#187]
Logo is made, looks awesome, and is on the readme and the main site banner

Test Checklist:
- [x] Test Analysis & discussion with developer
- [x] Write Test Cases / Charters
- [x] Test Cases & Charters Reviewed
- [x] Test Cases Executed
- [x] Test Charters Executed
- [x] Regression tests executed
- [x] Automation Tests added to project

**Comment by mwalker-scottlogic** [comment]
### Test Analysis

- Only automation required is to check banner on both city and summary page to see if logo is visible ✅
