### ISSUE TITLE
Update in_situ_data stored to include the source each measurement was taken

### ISSUE THREAD

**Issue by amehta-scottlogic** [ECMWFCode4Earth/vAirify#20]
## Acceptance Criteria

- Investigate possible sensor_types, entities and other fields from open AQ to see what might be interesting to store/useful for users to see
- Bring findings to team and decide what we will store
- Each document in the in_situ_data collection has a field 'api_source' (with value OpenAQ) + other fields that have been decided
- entity and data_sensor_type should be appear in each document.

Test Checklist:
- [x] Test Analysis & discussion with developer
- [x] Write Test Cases / Charters
- [x] Test Cases & Charters Reviewed
- [x] Test Cases Executed
- [ ] Charter Executed
- [x]  Regression tests executed
- [ ] Write Automation tests for regression

**Comment by mnyamunda-scottlogic** [comment]
**Test Analysis** 

- Verify that api_source can be seen within the database. Will we need to actually have a different source to properly test that this works? eg run from openAQ and then from a different source. Can be automated. (Only certain data types allowed as values)
- sensor_type Verify that this is correctly shown. Will we need other sensor types to know that the value is correct? Can be automated (only certain data types allowed as values)

**Comment by mnyamunda-scottlogic** [comment]
TC execution revealed a third contender for sensor_types. "low-cost sensor" What is the difference between that and "low cost"?

**Comment by mnyamunda-scottlogic** [comment]
Test Cases executed. Waiting on integration tests.
