### ISSUE TITLE
[5 day spike] Investigate performance issues and try and fix

### ISSUE THREAD

**Issue by rstrange-scottlogic** [ECMWFCode4Earth/vAirify#220]
We are sometimes seeing significant slowdown on the single city page, we would like to dig into this and work out what's causing it, and potentially put forward some fixes.

This might be that we put a limit on the amount of data we display, or we might be able to improve the efficiency of some of the code. Alternatively it might be certain browsers (?) 

- This should take within 5 seconds for Los Angeles on July 4th on Tim's laptop (Forecast Base Date set to 04/07/2024 12:00)

Test Checklist:
- [x] Test Analysis & discussion with developer
- [x] Write Test Cases / Charters
- [ ] Test Cases & Charters Reviewed
- [x] Test Cases Executed
- [ ] Test Charters Executed
- [x] Regression tests executed
- [ ] Automation Tests added to project

**Comment by Ben-EJ** [comment]
[Speed Testing Report.docx](https://github.com/user-attachments/files/16362799/Speed.Testing.Report.docx)

**Comment by mwalker-scottlogic** [comment]
### Test Analysis

- The only AC is 'This should take within 5 seconds for Los Angeles on July 4th on Tim's laptop (Forecast Base Date set to 04/07/2024 12:00)', therefore @Tim Johnson will be able to advise on if this passes acceptance testing
- The ticket needs to pass the regression run

**Comment by tjohnson-scottlogic** [comment]
Page & data loaded within 1s for the specified city & time, so meets the acceptance criteria.

**Comment by mwalker-scottlogic** [comment]
### Regression - PASSED

- Frontend

![Image](https://github.com/user-attachments/assets/9ba190c7-0d77-4a4d-97b2-5c74c176c4f4)

[Playwright Regression 29.07.24.pdf](https://github.com/user-attachments/files/16415142/Playwright.Regression.29.07.24.pdf)

- Backend

![Image](https://github.com/user-attachments/assets/b8e591ec-c5ba-4d28-8f49-93b82a2c05ba)
