### ISSUE TITLE
Create an API to query forecast data

### ISSUE THREAD

**Issue by amehta-scottlogic** [ECMWFCode4Earth/vAirify#24]
## Acceptance Criteria

- An API exists with details: GET /air-pollutant/forecast
- Required query parameters should be valid_time_from, valid_time_to, location_type, base_time
- Optional query parameters should be location_name
- Response should be JSON array with following fields in each document:
  |Field|Value from database|
  |--------|--------|
  | base_time | forecast_base_time |
  | valid_time | forecast_valid_time |
  | location_type | location_type |
  | location_name | name  |
  | overall_aqi_level | overall_aqi_level |
  | no2 | no2 object |
  | o3 | o3 object |
  | pm2_5 | pm2_5 object |
  | pm10 | pm10 object |
  | so2 | so2 object |

 | Input | Format |
 |--------|--------|
 | valid_time_from | YYYY-MM-DDThh:mm:ss.sssZ |
 | valid_time_to | YYYY-MM-DDThh:mm:ss.sssZ |
 | base_time | YYYY-MM-DDThh:mm:ss.sssZ |
 | location_type | string, all lower case |
 | location_name | string, capital letter at beginning |

For this ticket to be done it must include automation

Test Checklist:
- [x] Test Analysis & discussion with developer
- [x] Write Test Cases / Charters
- [x] Test Cases & Charters Reviewed
- [x] Test Cases Executed
- [ ] Test Charters Executed
- [x] Regression tests executed
- [ ] Automation Tests added to project

**Comment by mwalker-scottlogic** [comment]
Regression tests executed 05/06

**Comment by mwalker-scottlogic** [comment]
### Test Analysis - DRAFT
Test Case required:

- Verify it can return small amount of data
- Verify that it can return a large amount of data

- Verify `valid_time_from`, `valid_time_to`, `location_type` & `base_time` are required parameters
  - Expect happy path response with all required parameters being valid and there being corresponding data in the database
  - Expect unhappy path response with permutations of required parameters being:
    -  invalid --> use charter for different ways this can be invalid
    - missing
    - empty
    - null
- Verify `location_name` is an optional parameter
  -  Expect happy path response with all required parameters & the optional parameter being valid and there being corresponding data in the database
  - Expect unhappy path response with all required parameters being valid and optional parameter being
    -  invalid --> use charter for different ways this can be invalid
    - empty
    - null
  - Verify happy path response matches JSON schema
  - Verify unhappy path matches schema -->what is the unhappy path schema?

Test Charter:

- Explore forecast data API with permutations of required and optional parameters to discover if this is working as expected
- Explore forecast data API with different inputs to discover input validity


Regression candidate:

- Yes

**Comment by mwalker-scottlogic** [comment]
### FINDING - `valid_date_to` doesn't seem to include the upper bound

Steps to reproduce:

- Postman GET request to `air-pollutant/forecast` endpoint with 
  - `forecast_base_time` set to a datetime that overlaps with data in your forecast_data database e.g 2024-06-06T00%3A00%3A00.000%2B00%3A00
  - `valid_date_from`  set to the same as `forecast_base_time`
  - `valid_date_to` set to the top end of the expected forecast eg 2024-06-11T00%3A00%3A00.000%2B00%3A00
  - `location_type` = city
  - `location_name` set to a city in the locations database
- search the response for the city name
- query the mongo database for the forecast base time and city
- compare the number of items

Expected:

- Same number of items

Actual

- One less in the API response, the missing data being the upper bound of the date range

**Comment by mwalker-scottlogic** [comment]
### Finding

- the AC for this ticket has a `valid_time` key, but we have implemented `valid_date`

Steps to reproduce:

- Look in the `forecast_data` database, observe the `valid_date` key

**Comment by mwalker-scottlogic** [comment]
### Findings

- Discoveries from exploratory testing ([see notes](https://github.com/ECMWFCode4Earth/vAirify/wiki/Charter-7:-Explore-forecast-data-API-with-different-inputs-to-discover-input-validity))
- `valid_date_from`, `valid_date_to`, `forecast_base_time` can all take numbers as parameter values, including negative numbers, with a 200 status

![Image](https://github.com/ECMWFCode4Earth/vAirify/assets/110834691/e3f39c9d-2676-4dcc-bb80-c8b31ad1e854)

- using a year of 0000 in the datetime gets a 500 error for all date parameters

![Image](https://github.com/ECMWFCode4Earth/vAirify/assets/110834691/d501c9ce-cc02-4b8a-8675-a50e1f4f5f53)

- `location_name` does not seem to have any kind of validation, you can use for example <>, /, - returning an empty array with status 200
- you can send a body, I was able to send a json and a 10 paragraph string
- it works with no headers

**Comment by mwalker-scottlogic** [comment]
### Finding

Required query param names are not all correct:

- should be `valid_time_from`, `valid_time_to`, `location_type`, `base_time`
- actually are `valid_date_from`, `valid_date_to`, `location_type`, `forecast_base_time`

**Comment by amehta-scottlogic** [comment]
> ### Findings
> * Discoveries from exploratory testing ([see notes](https://github.com/ECMWFCode4Earth/vAirify/wiki/Charter-7:-Explore-forecast-data-API-with-different-inputs-to-discover-input-validity))
> * `valid_date_from`, `valid_date_to`, `forecast_base_time` can all take numbers as parameter values, including negative numbers, with a 200 status
> 
> ![Image](https://private-user-images.githubusercontent.com/110834691/338576975-e3f39c9d-2676-4dcc-bb80-c8b31ad1e854.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODUxODgsIm5iZiI6MTcxODE4NDg4OCwicGF0aCI6Ii8xMTA4MzQ2OTEvMzM4NTc2OTc1LWUzZjM5YzlkLTI2NzYtNGRjYy1iYjgwLWM4YjMxYWQxZTg1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwOTM0NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTU3N2E2MWQ5M2U1YTE2NmFjMjMxZmIxMTA4OGFjYTQ3YzBkY2U5ZDIzYWY0OTVjYWQ3MGE3ZjBiZmYwYTExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dv4C0HZmVmCtM_UVRxsHwYgc5hQ02U1xeWdhx6qIekY)
> 
> * using a year of 0000 in the datetime gets a 500 error for all date parameters
> 
> ![Image](https://private-user-images.githubusercontent.com/110834691/338576807-d501c9ce-cc02-4b8a-8675-a50e1f4f5f53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODUxODgsIm5iZiI6MTcxODE4NDg4OCwicGF0aCI6Ii8xMTA4MzQ2OTEvMzM4NTc2ODA3LWQ1MDFjOWNlLWNjMDItNGI4YS04Njc1LWE1MGUxZjRmNWY1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwOTM0NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDcyYzQxZWM3ZjY4YzE0NmJlYzgzZDEwMDQ0NjExMmQ1MTI5NWY2ZGU5YjFmNWNmZmYwZjU4NDEwZjVkNWE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z3BHq7Z40kb2SV7wlX3L1ByPj5KEALVnzqQ2_uk7R68)
> 
> * `location_name` does not seem to have any kind of validation, you can use for example <>, /, - returning an empty array with status 200
> * you can send a body, I was able to send a json and a 10 paragraph string
> * it works with no headers
> * I dropped the collection in MongoDB, I got back an empty array and a 200 response

My opinion on findings:
- numbers as parameter values for dates - no change needed
- year of 0000 - no change needed
- location_name validation - no change needed
- sending a body - no change needed
- no headers - no change needed
- dropped collection - no change needed

**Comment by amehta-scottlogic** [comment]
> ### Finding
> Required query param names are not all correct:
> 
> * should be `valid_time_from`, `valid_time_to`, `location_type`, `base_time`
> * actually are `valid_date_from`, `valid_date_to`, `location_type`, `forecast_base_time`

Agreed with this - will make changes

**Comment by amehta-scottlogic** [comment]
> ### Finding
> * the AC for this ticket has a `valid_time` key, but we have implemented `valid_date`
> 
> Steps to reproduce:
> 
> * Look in the `forecast_data` database, observe the `valid_date` key

Also should be fixed

**Comment by mwalker-scottlogic** [comment]
- `forecast_api_seeded_data_tests.py` tests now passing
- `forecast_api_validation_tests.py` tests now passing
