### ISSUE TITLE
Date picker only fires when the time is changed/selected

### ISSUE THREAD

**Issue by rstrange-scottlogic** [ECMWFCode4Earth/vAirify#246]
Currently the date picker appears to be firing when the date is selected, as opposed to waiting for the time to be selected as well. The data reloads while the control is still showing the date and time selection popup.

We would like to delay the select until the time has also been selected, so users have to 'finish' with the control before the data query is fired.

Ideally we would have an ok button outside the date control that determines when the date change takes effect.

- Playwright tests updated

**Comment by lincent** [comment]
What I'll be testing - 
1. Select new date - no data update
2. Select new time - no data update
3. click ok button - displayed updates

Do the above on both summary page and city page.

**Comment by mwalker-scottlogic** [comment]
@lincent There are api call specs for both the city and summary pages which make assertions on API calls that are triggered. You should be able to re-use the methodology to assert `requestArray.length` is zero for above checks 1-5, and that the correct api call is made for check 6
