### ISSUE TITLE
BUG - Measurement above max pollutant value breaks AQI graph

### ISSUE THREAD

**Issue by mwalker-scottlogic** [ECMWFCode4Earth/vAirify#255]
Steps to reproduce:

- mock data to provide a measurement and forecast discrepency for a location at a given time that is the maximum, where the mesurement for the pollutant is higher than the upperbound of the AQI 6
- load the city page for the location

Expected:

- The page loads and the AQI graph shows the value as AQI 6

Actual:

In reality the page never loaded at all due to an infinite loop, but by taking the offending graph out of the page you would have seen something like

![Image](https://github.com/user-attachments/assets/c53a36ee-513c-48d7-b6f9-d42665832e15)

  Test Checklist:
- [x] Test Analysis & discussion with developer
- [ ] Write Test Cases / Charters
- [ ] Test Cases & Charters Reviewed
- [ ] Test Cases Executed
- [ ] Test Charters Executed
- [x] Regression tests executed
- [ ] Automation Tests added to project

**Comment by mwalker-scottlogic** [comment]
### Test Analysis

Test charter - Explore UI with pollutant values greater than AQI 6 to discover reliability:
- set up mock data with pollutant values above max threshold - setting up the data can be part of the testing session (it has a timebox of 45-90 mins normally but this is a small piece of work so if this takes less time that is ok)
- check that the page loads
- check that the values represented on the graph are for AQI 6
- check different pollutants
- double check that this data doesn't break the summary table

Automation required:
- set up a snapshot test using the same data as above so we can assert AQI graph continues to work this way, on all 3 key browsers

**Comment by mnyamunda-scottlogic** [comment]
Makes good sense !

**Comment by lincent** [comment]
Testing charter record - https://github.com/ECMWFCode4Earth/vAirify/wiki/Charter-22:-Explore-high-measurement-values
