### ISSUE TITLE
BUG - logo broken locally

### ISSUE THREAD

**Issue by mwalker-scottlogic** [ECMWFCode4Earth/vAirify#270]
Steps to reproduce:

- pull main
- delete ui container and nodemodules image
- rebuild
- navigate to http://localhost:5173/city/summary

Expected:
- same as deployed version

![Image](https://github.com/user-attachments/assets/dd285a17-35f5-4929-9c6c-bc30ec0b8f01)

Actual:

- chrome

![Image](https://github.com/user-attachments/assets/9dd34ce7-6996-46d8-bde7-fa7899bc1224)

- firefox

![Image](https://github.com/user-attachments/assets/2acbc7ef-5f87-454f-950b-05e20052d3ec)

Test Checklist:
- [x] Test Analysis & discussion with developer
- [x] Write Test Cases / Charters
- [x] Test Cases & Charters Reviewed
- [x] Test Cases Executed
- [ ] Test Charters Executed
- [x] Regression tests executed
- [x] Automation Tests added to project

**Comment by mwalker-scottlogic** [comment]
Regression -  31/07 PASSED ✅ 

- Frontend:

![Image](https://github.com/user-attachments/assets/a1cea07a-83c0-4cbc-830a-d8d4d8316f6a)

[Playwright Regression 31.07.24.pdf](https://github.com/user-attachments/files/16444382/Playwright.Regression.31.07.24.pdf)

- Backend:

![Image](https://github.com/user-attachments/assets/e6b672e6-fdca-48c1-ac84-4e9428a59330)

**Comment by mwalker-scottlogic** [comment]
### Test Analysis
Only testing required here is to update the test that checks the logo is visible to be a screenshot test, and to pass regression ✅

**Comment by mnyamunda-scottlogic** [comment]
Agreed! 💯
