### ISSUE TITLE
Switch association mechanism for forecast data to city to use bilinear interpolation

### ISSUE THREAD

**Issue by amehta-scottlogic** [ECMWFCode4Earth/vAirify#3]
## Description

Mentors have said they currently use bilinear interpolation on a city's coordinates to calculate the pollutant values to use from forecast data.

At the moment we're using nearest, so let's change it to be in sync

## Acceptance Criteria
- We use bilinear interpolation as the method to associated city with pollutant forecast data

Test Checklist:
- [x] Test Analysis & discussion with developer
- [x] Write Test Cases / Charters
- [x] Test Cases & Charters Reviewed
- [ ] Test Cases / Charters Executed
- [x] Regression tests executed
- [ ] Write Automation tests for regression

**Comment by mwalker-scottlogic** [comment]
**Given** there is a city with latitude and longitude
**When** the forecast process is run
**Then** the data associated with the city is done via bilinear interpolation

**Comment by mwalker-scottlogic** [comment]
Only regression tested forecast db as in_situ is too unstable
