### ISSUE TITLE
Make application work from command line

### ISSUE THREAD

**Issue by amehta-scottlogic** [ECMWFCode4Earth/vAirify#31]
@sebsteinig reported that running the application via command line isn't working due to not being able to find the src directory.

Acceptance Criteria
- Ensure the application is runnable via command line as well as through PyCharm
- In README - document how to run the applications via command line

Could look into moving scripts into root of repo/adding src to python path

Test Checklist:
- [x] Test Analysis & discussion with developer
- [x] Write Test Cases / Charters
- [x] Test Cases & Charters Reviewed
- [x] Test Cases / Charters Executed
- [ ] Write Automation tests for regression

**Comment by mnyamunda-scottlogic** [comment]
**Test Analysis**

- Verify functionality of different CLI options, PyCharm, GitBash , Powershell = TC
- Verify that environment can be configured. Exploratory? test different.
- Verify functionality with change of src directory.

**Comment by mnyamunda-scottlogic** [comment]
Test Analysis
- Test various different CLI options. Powershell, PyCharm, Gitbash 
- Verify that the run can be configured into a specific environment?

- Regression for the src folder change.

**Comment by mnyamunda-scottlogic** [comment]
Previous issues resolved following steps 2 to 3 inside README.
 
paste "conda activate air-quality-dev" manually as opposed to clicking play btn
