### ISSUE TITLE
Create an API to query in situ data for summary page

### ISSUE THREAD

**Issue by amehta-scottlogic** [ECMWFCode4Earth/vAirify#32]
## Description

The first screen in the dashboard is going to show 10 cities where the forecasted and in situ values are most different. This will be done for a specific `forecast_base_time` and `forecast_valid_time`

 To do this we need to actually calculate this from the data in our database.

## Acceptance Criteria

- An API exists with details: GET /air-pollutant/measurements/summary
- `location_type` and `measurement_base_time`  & `measurement_time_range` are validated and if not valid we'll return 422
- Success will return 200
- Required query parameters should be `location_type`, `measurement_base_time`, `measurement_time_range`
- Measurements should be:
  - grouped together for each location where they are +/- 1.5 hours around the forecast valid time
  - averages will use the mean
  - an average pollutant value should be taken for these and AQI calculated accordingly (reuse current code)
  - overall AQI is then calculated for each of these (reuse current code)
  - the time assigned is the `measurement_base_time`
- Response should be JSON array with items of structure:
```
{
    "measurement_base_time": "2024-06-06T09:00:00+00:00",
    "location_type": "city",
    "location_name": "Brussels",
    "overall_aqi_level": {
      "mean": 2,
      "median": 2
    },
    "no2": {
      "mean": {
        "aqi_level": 1,
        "value": 26.439393939393938
      },
      "median": {
        "aqi_level": 1,
        "value": 24
      }
    },
    "o3": {
      "mean": {
        "aqi_level": 1,
        "value": 49.69047619047619
      },
      "median": {
        "aqi_level": 1,
        "value": 47
      }
    },
    "pm2_5": {
      "mean": {
        "aqi_level": 2,
        "value": 18.806401519968052
      },
      "median": {
        "aqi_level": 2,
        "value": 17.39
      }
    },
    "pm10": {
      "mean": {
        "aqi_level": 2,
        "value": 32.496022749428796
      },
      "median": {
        "aqi_level": 2,
        "value": 30
      }
    },
    "so2": {
      "mean": {
        "aqi_level": 1,
        "value": 4.211111111111111
      },
      "median": {
        "aqi_level": 1,
        "value": 4.85
      }
    }
  },
```
Test Checklist:
- [x] Test Analysis & discussion with developer
- [x] Write Test Cases / Charters
- [x] Test Cases & Charters Reviewed
- [x] Test Cases Executed
- [x] Test Charters Executed
- [x] Regression tests executed
- [x] Automation Tests added to project

**Comment by mwalker-scottlogic** [comment]
### Test Analysis


- Undertake an initial sense check using Postman
- Create automation using Pytest with Request library for functional test cases
- POISED testing heuristic applied


**Parameters:**
**Output:**


**Interoperability:**

**Security:**

**Errors:**

**Data:**


Test Charter:


Regression candidate:

- Yes

**Comment by mwalker-scottlogic** [comment]
### Findings - Charter 9 Test Execution

- for details of what was explored see [here](https://github.com/ECMWFCode4Earth/vAirify/wiki/Charter-9:-Explore-Summary-In-Situ-API-with-creative-parameters-and-headers-to-discover-surprises)
- if 'location_type` is a long paragraph, "msg": "Input should be 'city'". If always needs to be city, why have it as a param if it is always the same and required
- `measurement_time_range:`
  -   can be negative
  - decimal problem 1.0 is 200OK vs 1.5 is a 422
  - whitespace permitted (e.g.' 1' works)
- you can send a body with the API call e.g {"foo": "bar"}
