### ISSUE TITLE
Create Test Strategy

### ISSUE THREAD

**Issue by amehta-scottlogic** [ECMWFCode4Earth/vAirify#4]
Create a high level test strategy

- An example from Challenge 24 team [here](https://scottlogic.atlassian.net/wiki/spaces/WF/pages/4263804960/Test+Strategy+-+Challenge+24)
- This ticket will require: 
  - researching the elements required to create a test strategy (possibly using the ISTQB Certified Tester syllabus to guide)
  - updating the model of the system created in the first week with any new information from our research
  - writing a test strategy
  - highlighting any TBC areas requiring more information from the mentors
  - getting a peer review?

**Comment by mwalker-scottlogic** [comment]
Initial strategy created, in peer review from Max & Rich Rogers
