### ISSUE TITLE
Add retry logic to Open AQ fetch

### ISSUE THREAD

**Issue by amehta-scottlogic** [ECMWFCode4Earth/vAirify#45]
## Acceptance Criteria

- If response from OpenAQ times out, retry the request to a max of 3 times
- No need for any backoff or waits between tries
- The city and URL that the request failed for is logged only if it fails three times

Test Checklist:
- [ ] Test Analysis & discussion with developer
- [ ] Write Test Cases / Charters
- [x] Test Cases & Charters Reviewed
- [ ] Test Cases Executed
- [ ] Test Charters Executed
- [x] Regression tests executed
- [x] Automation Tests added to project

**Comment by mwalker-scottlogic** [comment]
forecast_api_seeded_data_tests.py, forecast_api_validation_tests.py, cams_known_grib_test.py, forecast_calibration_tests.py & open_aq_etl_tests.py tests all passed.

Executed manual test cases, had to make some changes to test assertions, but expected behaviour was observed

**Comment by mwalker-scottlogic** [comment]
Automation added by @rstrange-scottlogic to cover:

- 3 timeouts creates an error and a log
- 1 timeout followed by success doesn't error or log
- A non timeout error doesn't retry, errors and logs
