### ISSUE TITLE
Open AQ Unit conversion

### ISSUE THREAD

**Issue by amehta-scottlogic** [ECMWFCode4Earth/vAirify#46]
OpenAQ can report pollutant values with different units. So far we have seen ppm and µg/m³. We want all db units to be µg/m³

- Look at volume for ppm/ugm3 (if neglible just ignore)
- Otherwise look for different data sources if exists

## Acceptance Criteria
- When data is received in ppm, filter these measurements out

Test Checklist:
- [x] Test Analysis & discussion with developer
- [x] Write Test Cases / Charters
- [x] Test Cases & Charters Reviewed
~~- [ ] Test Cases executed~~
- [x] Test Charters Executed
- [x] Regression tests executed
- [ ] Write Automation tests for regression

**Comment by mwalker-scottlogic** [comment]
### Test Analysis
To test:

- This work is being reverted in https://github.com/ECMWFCode4Earth/vAirify/issues/63, therefore testing limited to:
  - Full regression run to ensure that this change has not affected prior work
  - Check to ensure ppm is not being used

Test Case required:

- N/A as this work is being reverted, the test effort will be exploratory

Test Charter:

- Explore the in situ database in conjunction with Postman to discover if the correct data is being filtered based on units


Regression candidate:

No

**Comment by mwalker-scottlogic** [comment]
Regression tests executed and passed (except one test regarding git bash however this is being investigated.

Test charter executed supporting that the PPM filtering is working as expected https://github.com/ECMWFCode4Earth/vAirify/wiki/Charter-5:-Explore-the-in-situ-database-in-conjunction-with-Postman-to-discover-if-the-correct-data-is-being-filtered-based-on-units
