### ISSUE TITLE
Create an API to query in situ data for single city page

### ISSUE THREAD

**Issue by amehta-scottlogic** [ECMWFCode4Earth/vAirify#47]
## Acceptance Criteria

- An API exists with details: GET /air-pollutant/measurements
- Required query parameters should be date_from, date_to, location_type
- Optional query parameters should be location_names (this can support multiple parameters comma separated), api_source
- Parameters are validated and if not valid we'll return 422
- Success will return 200
- Response should be JSON array with following fields in each document:
  |Field|Value from database|
  |--------|--------|
  | measurement_date | measurement_date |
  | location_type | location_type |
  | location_name | name  |
  | no2 | no2 value |
  | o3 | o3 value|
  | pm2_5 | pm2_5 value|
  | pm10 | pm10 value|
  | so2 | so2 value |
  | entity | metadata.entity |
  | sensor_type | metadata.entity |
  | site_name | location_name |
- Mongo Query performance is analysed and index is confirmed to be being used

For this ticket to be done it must include automation

Test Checklist:
- [x] Test Analysis & discussion with developer
- [x] Write Test Cases / Charters
- [x] Test Cases & Charters Reviewed
- [x] Test Cases Executed
- [x] Test Charters Executed
- [x] Regression tests executed
- [x] Automation Tests added to project

**Comment by mnyamunda-scottlogic** [comment]
Test Analysis

- Verify single city data displayed matches that of the database. (side by side with mongo db)
(Investigate regularity of new document upsertion/modification.

- Verify backend error logging. User must be lead to the happy path when entering wrong query
  e.g. entering only one 1/3 and 2/3 required parameters.
   -> only measurement_date_from and measurement_date_to
   -> only measurement_date_from and location_type 
   -> only measurement date_to and location type
        User must be made aware of the missing parameter each time.

**Comment by mwalker-scottlogic** [comment]
`forecast_api_seeded_data_tests.py`, `forecast_api_validation_tests.py`, `cams_known_grib_test.py`, `forecast_calibration_tests.py` & `open_aq_etl_tests.py` tests all passed.

Executed manual test cases, had to make some changes to test assertions, but expected behaviour was observed

**Comment by mwalker-scottlogic** [comment]
### Finding - `location_names` param spelled incorrectly

Expected:

- needs to be `location_names`

Actual:

- needs to be `location_name`

**Comment by mwalker-scottlogic** [comment]
### Exploratory testing Findings

[Charter 11: Explore GET air‐pollutant measurements In Situ API with creative parameters and headers to discover surprises](https://github.com/ECMWFCode4Earth/vAirify/wiki/Charter-11:-Explore-GET--air%E2%80%90pollutant-measurements-In-Situ-API-with-creative-parameters-and-headers-to-discover-surprises) ✅ 

- `date_from` and `date_to`
  - 500 internal server error if you set the year to 0000
  - Can send a number as a date (+/-)
- `location_names` and `api_sources` don't seem to have any validation

**Comment by mwalker-scottlogic** [comment]
### Finding - `api_source` 500

Steps to reproduce:

- Make a GET call to `/air-pollutant/measurements` endpoint with `date_from` (valid Datetime), `date_to` (valid Datetime), `location_type` (city) parameters  and `api_source` set to 'OpenAQ'
- Make a GET call to `/air-pollutant/measurements` endpoint with `date_from` (valid Datetime), `date_to` (valid Datetime), `location_type` (city) parameters  and `api_source` set to 'openaq'
- e.g http://127.0.0.1:8000/air-pollutant/measurements?date_from=2024-06-21T14%3A00%3A00.000%2B00%3A00&date_to=2024-06-21T16%3A00%3A00.000%2B00%3A00&location_type=city&api_source=OpenAQ

Expected:

- data returned, status 200

Actual:

for OpenAQ: 
422 status code
![Image](https://github.com/ECMWFCode4Earth/vAirify/assets/110834691/a9c483b0-3b0b-459d-814d-e05e44457240)

for openaq:
500 status code


![Image](https://github.com/ECMWFCode4Earth/vAirify/assets/110834691/d7c3373d-87d1-4253-b164-c84bb734ec7f)

**Comment by mwalker-scottlogic** [comment]
We discovered that if you send a request to the `air-pollutant/measurements` endpoint and have seeded in the `in_situ` database data which has an `api_source` that also isn't "OpenAQ" you get a 500 response. This has been determined to be expected behaviour so tests have been added for this to make sure this continues. We need to prevent incorrect data entering the database using schema validation which has a ticket in the backlog
