### ISSUE TITLE
As a tester I have an automated integration test suite for the CAMs ETL pipeline so that system quality does not regress

### ISSUE THREAD

**Issue by rstrange-scottlogic** [ECMWFCode4Earth/vAirify#55]
Acceptance Criteria:

* We have a test suite that can :
  * Mock out or use known GRIB files to ensure the CAMs data is a known, static state
  * Run the ETL pipeline
  * Use a known separate database
  * Check the values written to the database are as expected.
* For this story we will only create one test covering multiple (small number) locations and all pollutants.
* For now this can just be automated and run locally. We will look to target the tests at a deployed environment in time, will be a different ticket.

**Comment by mnyamunda-scottlogic** [comment]
Basic process

- run_etl_process -> stub actual call (return our GRIBS) instead and then we can assert exact values.

**Comment by mnyamunda-scottlogic** [comment]
In terms of regression we target specific documents and assert the values shown in the database. Failure of these tests would simple be an alert that the code has changed in terms of the etl process.

Plans to use some xarray functionality to grab a raw value from our GRIB. Then to manually go through all the calculations and store it as a variable. Then we assert that variable matches whatever we have within our database. As opposed to asserting a value such as 10.321472471264862.

**Comment by mnyamunda-scottlogic** [comment]
Extra modifications to run_forecast_etl to allow overriding of base date and time from default value.
