### ISSUE TITLE
Investigate in situ data issues/quality and other sources

### ISSUE THREAD

**Issue by amehta-scottlogic** [ECMWFCode4Earth/vAirify#6]
Analysis of OpenAQ in situ data for cities provided + other data sources

**Comment by amehta-scottlogic** [comment]
After our call with the mentors we discussed:
- We need to continue investigation into additional data sources - [purple air](https://community.purpleair.com/c/data/7) or [world aq](https://aqicn.org/city/beijing/) are options
- Storing more metrics such as max, min, avg etc for a given city to indicate range
- Maintaining the source of where data is coming from
- Developing some screening for very obvious values we would want to exclude like -1000 etc.

**Comment by amehta-scottlogic** [comment]
- aqicn is free but only provides AQI level (and not the same AQI we use currently)
- purpleair will cost money and their API isn't the best

**Comment by mwalker-scottlogic** [comment]
### Test Analysis
No test needed on this, spoke with @amehta-scottlogic
