### ISSUE TITLE
As a system user I want to compare the forecast and in situ data for a single city (Part 1)

### ISSUE THREAD

**Issue by amehta-scottlogic** [ECMWFCode4Earth/vAirify#60]
## Description

This page will be used to compare forecast/in situ for a single city.

This ticket has scope only for the displaying the forecast in the UI for a single city

We have decided to use echarts for the charting library for now. 

For now let's not use redux, something like this might be simpler: https://tanstack.com/query/latest/docs/framework/react/guides/queries

## Acceptance Criteria

- Under route /city/{city_name}, the UI will show the a line chart showing forecast data for a city
  - X axis = time, every 3 hours, Y axis = AQI level
  - Use API /air-pollutant/forecast to fetch forecast data for city
  - Data should be for 5 day range, forecast_base to forecast_base + 5
  - A loading indicator should be shown whilst fetching the data (check if echarts has something like this for the chart itself, otherwise overall spinner could be used)

Test Checklist:
- [x] Test Analysis & discussion with developer
- [x] Write Test Cases / Charters
- [ ] Test Cases & Charters Reviewed
- [ ] Test Cases Executed
- [ ] Test Charters Executed
- [x] Regression tests executed
- [ ] Automation Tests added to project

**Comment by mnyamunda-scottlogic** [comment]
Test Analysis

- Verify that mocked API data is displayed appropriately on the graph (manual) 
     -> Can then be automated as a screenshot assertion in playwright
        -> It seems only graphs with both forecast and in-situ are displayed. 
- Verify that the only graphs shown consist of a pollutant with both required measurements. ( May be a different mock file specifically for graphs)
-  Verify that data shown only spans 5 days
    

![Image](https://github.com/ECMWFCode4Earth/vAirify/assets/142179888/ca11b451-8181-4714-bdb1-6276fe942c45)

Additionally mock these time/dates to prevent oddities in graphs.

**Comment by mnyamunda-scottlogic** [comment]
FIndings
- On mocked data if user is zoomed in and deletes a line they are zoomed out.

**Comment by mwalker-scottlogic** [comment]
Analysis review - worth checking the scope of this ticket. The ticket title and description don't align. Is it just the forecast AQI plot? If so is it just the overall AQI or pollutant level AQIs too?

**Comment by mnyamunda-scottlogic** [comment]
Loading Icon is to be covered as a manual check as opposed to automation. Due to different browser behaviours.
