### ISSUE TITLE
As a tester I have an automated integration test suite for the In-Situ ETL pipeline so that system quality does not regress

### ISSUE THREAD

**Issue by amehta-scottlogic** [ECMWFCode4Earth/vAirify#67]
Acceptance Criteria:

We have a test suite that can :
- Mock out or use known files to ensure the In-Situ data is a known, static state
- Run the ETL pipeline
- Use a known separate database
- Check the values written to the database are as expected.
- For this story we will only create one test covering multiple (small number) locations and all pollutants.
- For now this can just be automated and run locally. We will look to target the tests at a deployed environment in time, will be a different ticket.

- Possible testing around being able to stub a file response with edited data to see if any issues arise.

**Comment by rstrange-scottlogic** [comment]
This has been done as part of another ticket
