### ISSUE TITLE
[UI] As a system user I want to see all measurement station data for a city so I can an analyse measurement data with more granularity

### ISSUE THREAD

**Issue by amehta-scottlogic** [ECMWFCode4Earth/vAirify#76]
## Acceptance Criteria

- A chart exists on the single city page that shows the measurements for all stations within the defined time period
- one chart per pollutant type
- one 'legend' that affects all (to allow selection/deselection of stations)
- Playwright test exists
  - Once tests are established remove 'fruit' code

Test Checklist:
- [x] Test Analysis & discussion with developer
- [x] Write Test Cases / Charters
- [x] Test Cases & Charters Reviewed
- [x] Test Cases Executed
- [x] Test Charters Executed
- [x] Regression tests executed
- [x] Automation Tests added to project

**Comment by mnyamunda-scottlogic** [comment]
Analysis

- Verify that the only graphs shown consist of a pollutant with both required measurements. ( May be a different mock file specifically for graphs)
- - Verify that the only graphs shown consist of a pollutant with both required measurements. ( May be a different mock file specifically for graphs)

**Comment by mnyamunda-scottlogic** [comment]
Passes manual regression checks

**Comment by mwalker-scottlogic** [comment]
Analysis review:
- 'Verify that the only graphs shown consist of a pollutant with both required measurements. (e.g. we have forecast and measurements)' is this a criteria?
- AC1, I think we should specify testing around different amounts of measurement stations

**Comment by mnyamunda-scottlogic** [comment]
Currently there is only AC for making sure that the legend exists. There is nothing covers the expected behaviour of the legend. 
- Regression has been written only for removing a station and then asserting that it is no longer shown beside the remaining sites.
- This could be a charter to click around on the sites and observe the behaviour. (prod and local)
