### ISSUE TITLE
[UI] Summary Table

### ISSUE THREAD

**Issue by amehta-scottlogic** [ECMWFCode4Earth/vAirify#85]
## Acceptance Criteria

- Summary page shows a table which has measurements/forecast data for all locations where measurements exist
- All pollutant values should be shown in ug/m3
- Overall AQI value should be shown as well as difference
- Table should be sorted in order of worst offenders desc - if equal positive comes first
- ag-grid is to round up each value to one decimal place

Test Checklist:
- [x] Test Analysis & discussion with developer
- [x] Write Test Cases / Charters
- [x] Test Cases & Charters Reviewed
- [ ] Test Cases Executed
- [ ] Test Charters Executed
- [x] Regression tests executed
- [ ] Automation Tests added to project

**Comment by mnyamunda-scottlogic** [comment]
Test Analysis.

Front landing page. The first thing user will see.

Verify that pollutants are shown accurately within UI. ug/m3
Verify worst offenders are sorted correctly (DESC) . This should be the highest delta in forecast and in-situ.

**Comment by mnyamunda-scottlogic** [comment]
Notes: Column starts out unevenly spaced. May need a default width which can later be manually spaced by user? (depends on screen size)

**Comment by mwalker-scottlogic** [comment]
`forecast_api_seeded_data_tests.py`, `forecast_api_validation_tests.py`, `cams_known_grib_test.py`, `forecast_calibration_tests.py` & `open_aq_etl_tests.py` tests all passed.

Executed manual test cases, had to make some changes to test assertions, but expected behaviour was observed
