### ISSUE TITLE
As a user I want to be able to access the logs

### ISSUE THREAD

**Issue by lincent** [ECMWFCode4Earth/vAirify#99]
Within the docker images the logging gets outputted into console, this ends up in the docker log.

For the ETL images this is triggered by supercronic and the logs get wrapped in supercronics logs, making it hard to read as there is too much meta-data.

This ticket should look at improving the logging. 

Acceptance Criteria
- Logs are preserved when docker containers get deleted/rebuilt
- Logs are separated by service
- logs are separated by day
- This covers the two ETL scripts and the API

Tests will be a manual verification that the logs are stored on the linux machine and persist when redeploying the docker images.

Test Checklist:
- [x] Test Analysis & discussion with developer
- [ ] Write Test Cases / Charters
- [ ] Test Cases & Charters Reviewed
- [ ] Test Cases Executed
- [ ] Test Charters Executed
- [x] Regression tests executed
- [ ] Automation Tests added to project

**Comment by mnyamunda-scottlogic** [comment]
Passes manual regression checks

**Comment by rstrange-scottlogic** [comment]
Tested this whilst looking into a defect. 

I was able to search through logs for a given part of the application:

sudo journalctl --since="today" CONTAINER_NAME=etl-forecast
sudo journalctl --since="today" CONTAINER_NAME=etl-insitu
sudo journalctl --since="today" CONTAINER_NAME=backend-api

I can search these for a given date:

sudo journalctl --since="2024-07-04" --until="2024-07-05" CONTAINER_NAME=etl-insitu

There was a deploy last Friday (2024-07-12) and these logs were still present so they have not been removed as a side effect.

**Comment by mwalker-scottlogic** [comment]
### Test Session 17/07/24

- SSH into box
- there was a deployment on 16/07 in the PM, check the logs for each container for 16/07 AM to check visible
  - forecast

![Image](https://github.com/user-attachments/assets/06ecbc69-4504-4525-96c5-d6b81010f2ef)

  - in situ

![Image](https://github.com/user-attachments/assets/0d046b9d-54e2-475f-be6d-98d55e117b9f)

  - backend api

![Image](https://github.com/user-attachments/assets/6531fdd6-d652-41e1-b3c1-b9758c49d801)

- delete containers, check the logs are visible
- e.g `sudo docker compose down etl-insitu`
  - forecast

[Image](https://github.com/user-attachments/assets/e512ac7f-50ba-4881-b109-c3dfefcb0552)

  - in situ

![Image](https://github.com/user-attachments/assets/44391ab8-6dea-43d5-a907-68133b1dfc82)

  - api

![Image](https://github.com/user-attachments/assets/434399f1-708a-48ed-a407-3639518e42d3)

- `docker compose up`

  - forecast

![Image](https://github.com/user-attachments/assets/181f4608-468e-4d62-9453-109df2793235)

  - in situ


![Image](https://github.com/user-attachments/assets/81c53e4c-d6c9-457c-a4bb-547aa6ce7c9c)

  - api


![Image](https://github.com/user-attachments/assets/31ddd3c3-ee90-4bd8-b08f-42457742b8fe)
